// File: settings.gradle

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Aggiungi JitPack qui, serve per MPAndroidChart
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "Sentieri"
include ':app'
include ':levo-sdk'
    