// File: /app/build.gradle

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'androidx.navigation.safeargs.kotlin'
}

android {
    namespace 'com.apstudio.sentieri'
    compileSdk 35
    // Usa la 34 che è l'ultima stabile, la 36 è in preview.

    defaultConfig {
        applicationId "com.apstudio.sentieri"
        minSdk 30
        targetSdk 35
        versionCode 25
        versionName '1.9.8'
    }

    buildFeatures {
        buildConfig true
        dataBinding true
        viewBinding true
        aidl true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    packaging {
        // Questa sezione è importante per evitare conflitti di licenze
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    // Forza tutte le dipendenze Kotlin ad allinearsi alla 2.0.0
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:2.0.0"))

    // Dipendenze di base STABILI
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.preference:preference-ktx:1.2.1'

    // Navigation STABILE
    def nav_version = "2.7.7"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    // Fragment & Activity STABILI
    implementation "androidx.fragment:fragment-ktx:1.8.1"
    implementation 'androidx.activity:activity-ktx:1.9.0'

    // Room STABILE
    def room_version = "2.6.1"
    implementation "androidx.room:room-runtime:$room_version"
    ksp "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"

    // Lifecycle STABILE
    def lifecycle_version = "2.8.3"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"

    // Coroutines STABILI
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1'

    // osmdroid & mapsforge
    implementation 'org.osmdroid:osmdroid-android:6.1.20'
    implementation 'org.osmdroid:osmdroid-mapsforge:6.1.20'
    implementation ('org.osmdroid:osmdroid-geopackage:6.1.20'){
        exclude group: 'org.osmdroid.gpkg'
        exclude module: 'ormlite-core'
        exclude group: 'mil.nga', module: 'sqlite-android'
    }

    // MPAndroidChart
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    // Altre
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.github.QuadFlask:colorpicker:0.0.13'

    // Test
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}

ksp {
    arg("room.generateKotlin", "true")
}
    